- incoming_data_path: "/home/noct/swing"
- num_workers: 40
- bigtable:
    project_id: "sktai-datahub"
    instance_id: "sktai-noct-poc"
    table_id: "noct-test"
    app_profile_id: "writer"
- logger:
    file: "my.log"
    level: "INFO"
    max_bytes: 512*1024*1024
    backup_count: 5
- metadata:
    file: "metadata.db"
