- incoming_data_path: "/swing/noct"
#- incoming_data_path: "/home/noct/noct-combiner/noct"
- num_workers: 40
#- report_interval: 60 * 60 * 24
- report_interval: 14400
- data_expiry: 150
- bigtable:
    project_id: "sktai-datahub"
    instance_id: "sktai-noct-poc"
    app_profile_id: "writer"
- logger:
    file: "my.log"
    level: "INFO"
    max_bytes: 512*1024*1024
    backup_count: 5
- metadata:
    rowkey_url: "http://etl.sktai.io/v1/swing_rowkey/"
    file: "metadata.db"
- slack:
    username: "noct-validation-bot"
    channel: "aidt-coe-swing-noti"
#    channel: "robert-bot"
    icon_emoji: ":x:"
