- server:
    num_workers: 32
- bigtable:
    project_id: "sktai-datahub"
    instance_id: "sktai-noct-poc"
    table_id: "noct-test"
- logger:
    file: "my.log"
    level: "INFO"
    max_bytes: 512*1024*1024
    backup_count: 5

